# Generated by Django 3.2.4 on 2021-06-29 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=8060, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=8060, null=True)),
                ('image', models.CharField(max_length=320)),
                ('is_marked', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=False)),
                ('is_history', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=8060, null=True)),
                ('is_marked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('done', 'Done')], default='todo', max_length=10)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task.board')),
            ],
            options={
                'ordering': ('-date_added',),
            },
        ),
    ]
