# Generated by Django 3.2.4 on 2021-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210625_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='visibility',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='user',
            name='plan_level',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10),
        ),
    ]
