# Generated by Django 3.2.4 on 2021-06-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210625_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quote',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
